[tools]
coreutils = "latest"
uv = "latest"
yq = "latest"

[env]
TC = "{{config_root}}/.toolchain/targets/arm-hisiv100-linux/bin"
SYSROOT = "{{config_root}}/rootfs"
CC = "{{config_root}}/.toolchain/targets/arm-hisiv100-linux/bin/arm-hisiv100-linux-uclibcgnueabi-gcc"