#!/usr/bin/env bash
#MISE description="Firmware extraction task for the LHA2104/8/8LC. Only supports 2104 right now :()"
mkdir -p build/roots
uv run tooling/extract.py 2104 firmware.bin build/roots
if [ "$1" != "dont-unsquash-the-filesystem" ]; then
    ROOTFSIMAGE=$(ls build/roots/*_rootfs | head -n1); 
    unsquashfs -d rootfs -f $ROOTFSIMAGE;
    APPFSIMAGE=$(ls build/roots/*_app | head -n1);\
    unsquashfs -d appfs -f $APPFSIMAGE
fi
#rm -rf build/rootfs