#!/usr/bin/env bash
#MISE description="Load a patch. Pass the file name as the first argument."
if $QUILT_PATCHSET = ""; then
    echo "Error: No patchset specified. Use "mise run set_patchset <patchset_name>" to set the patchset."
    exit 1
fi
export QUILT_PATCHES=sys/patches/$QUILT_PATCHSET
export QUILT_DIFF_OPTS="-p"
quilt push $1.patch
echo "Done! Patch loaded."