#!/usr/bin/env bash
#MISE description="Load a patch. Pass the file name as the first argument."
QUILT_ENV_DIR=.pc
QUILT_PATCHSET=$(cat $QUILT_ENV_DIR/.hd_patchset)
if [ "$QUILT_PATCHSET" = "" ]; then
    echo "Error: No patchset specified. Use 'mise run set_patchset [name]' to set the patchset.\n Wiping $QUILT_ENV_DIR directory."
    exit 1
fi
export QUILT_PATCHES="$(pwd)/sys/patches/$QUILT_PATCHSET"
export QUILT_DIFF_OPTS="-p"

cd "$(pwd)" || exit 1

# Verify the series file exists before calling quilt
if [ ! -f "$QUILT_PATCHES/series" ]; then
  echo "ERROR: Series file not found at $QUILT_PATCHES/series"
  exit 1
fi

quilt push -a
echo "Done! Patch loaded."