#!/usr/bin/env bash
#MISE description="Make a new patch. Pass the file name as the first argument."
export QUILT_PATCHES=sys/patches  
export QUILT_DIFF_OPTS="-p"
quilt new $1.patch
echo "Done! Use 'quilt add <file>' to add files to the patch. Run "mise run seal" to finish the patch."